### ISSUE TITLE
ext:autoloader deletes whole content of locallang.xlf and didn't create a new one (result is an exception)

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#12]
Everytime I recreate the file, the exception occurs after actuating "Flush system caches"

---

**#1278155988:** The path provided does not point to existing and accessible well-formed XML file. [More information](http://typo3.org/go/exception/CMS/debug/1278155988)
TYPO3\CMS\Core\Localization\Exception\InvalidXmlFileException thrown in file
/docker/code/typo3_src/typo3/sysext/core/Classes/Localization/Parser/AbstractXmlParser.php in line 99.

---
*TYPO3 version: 6.2.15*
*Autoloader version: 1.9.1*

---
It seems like the problem don't occur when I clear the autoloader cache via TYPO3 backend and all strings for `tt_content.content_element_name`and `tt_content.content_element_name.description` are present.
But I'm surprised that it is now necessary to add this in addition to the newly introduced strings `wizard.content_element_name.description`, `wizard.content_element_name`.

**Comment by lochmueller** [comment]
Hey @jousch ,

there was a second place with wrong "tt_content" labels:
https://github.com/lochmueller/autoloader/commit/feea9cfb2fcd295a5ffdef2bd00eed4ffe01d3c3
Now the `tt_content.[ELEMENT]` and `tt_content.[ELEMENT].description` is gone.

The problem, that the autoloader drop the whole content of the file is strange, because all autoloader components use "FileUtility::writeFileAndCreateFolder" to create the files. In the L10N context, the original file is loaded, just a string replace and the file is written to the disk. If the content is empty, the original file is also empty?!?!

Regards,
Tim
