### ISSUE TITLE
ContentObjects not working in Typo3 v11

### ISSUE THREAD

**Issue by benwick** [lochmueller/autoloader#189]
I use the following versions:

Autoloader: 7.3.6
Typo3: 11.5.10
Php: 8.0

A correct configured content object won't render with this setup. The class looks like this:

```
<?php

namespace My\Example\Domain\Model\Content;

use HDNET\Autoloader\Annotation\DatabaseTable;
use HDNET\Autoloader\Annotation\NoHeader;

/**
 * @DatabaseTable(tableName="tt_content")
 * @NoHeader
 */
class Box extends \TYPO3\CMS\Extbase\DomainObject\AbstractEntity {

}
```

A template exists. The rendering of the content object in the frontend will throw the following warning:

`Exception in content rendering: PHP Warning: Undefined array key "tx_example_domain_model_content_box" in typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapFactory.php line 224`

When I add the correct mapping in the extension file `example/Configuration/Extbase/Persistence/Classes.php`, the warning will go away. But this is not documented in any way.

**Comment by lochmueller** [comment]
Hey @benwick 

In the past, you have to use this loader: https://docs.typo3.org/typo3cms/extensions/autoloader/stable/Loader/ExtensionTypoScriptSetup.html But since Extbase do not handle this via TS anymore, your have to create this file: `Configuration/Extbase/Persistence/Classes.php` 
But keep in mind... there is already a Utility to generate the class schema: https://github.com/lochmueller/autoloader/commit/2ed12010ce68ee016f6a3b0d62f4c6495656b38f 

You can call this utility in this file. So you don't care if there are new Content-Object or Smart Objects, because they are added dynamically:
`return HDNET\Autoloader\Utility\ExtbasePersistenceUtility::getClassMappingForExtension('example');`

Feel free to add the information to the documentation and send a PR.

Regards,
Tim
