### ISSUE TITLE
[SUGGESTION] ContentObjects: FluidBackend Layout with definition list output 

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#2]
What about generating a sample `PluginNameBackend.html` with all properties (at least for properties with getters) with key and value style?

**Comment by lochmueller** [comment]
The basic problem is, that we generate the template once. After the template is generated and the developer extends the model, the new (or deleted - more critical) properties have to affect the backend template, but this is not the case. So a general output via f:debug is a good way to show the developer the function of the template. The problem also occurs if you change properties from e.g. string to \DateTime!! This results in an exception, because of the missing call of f:format.date. "Updateing" an existing template is no smart solution...
