### ISSUE TITLE
[FEATURE] Make it possible to disable default `tt_content.header` output in backend module `Page`

### ISSUE THREAD

**Issue by jousch** [lochmueller/autoloader#3]

**Comment by lochmueller** [comment]
Hey Jousch,
do you mean the header in the edit mode, or the header of the content element preview?
Regards,
Tim

**Comment by jousch** [comment]
The header of the content element preview. But of course, it would also be nice when `@noHeader’ is set, that the „normal“ header group is hidden and available within „Content data“ tab.

**Comment by lochmueller** [comment]
I close this issue. The backend preview should be customized by the fluid backend template. The TCA structure is TYPO3 "best practise" because the header element is always the same and is rendered content element independant in front of the element. As the result... I think the header should not use for custom elements.
