### ISSUE TITLE
Autoloader cache clear icon is broken under TYPO3 8.7.0

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/autoloader#80]

**Comment by cweiske** [comment]
This commit broke the icons of other extensions in TYPO3 v7.

By instantiating the IconRegistry in ext_localconf.php, the registry then knows no TCA tables, and thus cannot register icons for extension tables. (in v7).

Related: https://github.com/einpraegsam/powermail/issues/93

**Comment by lochmueller** [comment]
Hmm... I do not understand the problem. Yes... it could be tricky if there is a wrong order in the extension list (loading order). But this should not be the case, because a extension that is based on autoloader, should add autoloader as dependency, right?

It is a problem in current master too? Could you create a new issue and describe the problem in detail. Than I try to fix this shortly...

Regards,
Tim

**Comment by cweiske** [comment]
No, it's only a problem in TYPO3 v7. Since that is EOL anyway, my comment was only for historical purposes :)
